$ g++ try_catch.cpp
$ ./a.out
UserDefinedException caught!
Rethrowing...
Generalized exception caught!
